Name:           ros-indigo-safe-teleop-base
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS safe_teleop_base package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/safe_teleop_base
Source0:        %{name}-%{version}.tar.gz

Requires:       pcl-devel
Requires:       ros-indigo-base-local-planner
Requires:       ros-indigo-costmap-2d
Requires:       ros-indigo-roscpp
BuildRequires:  pcl-devel
BuildRequires:  ros-indigo-base-local-planner
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-costmap-2d
BuildRequires:  ros-indigo-roscpp

%description
This package provides automatic collision avoidance and is intended to be used
for safer teleoperation of a robot base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Jul 07 2017 Charles DuHadway (maintained by Benjamin Pitzer) <foo@foo.com> - 0.0.2-0
- Autogenerated by Bloom

* Fri Jul 07 2017 Charles DuHadway (maintained by Benjamin Pitzer) <foo@foo.com> - 0.0.1-0
- Autogenerated by Bloom

