transform_tolerance: 0.3
world_model: costmap
sim_time: 1.0
sim_granularity: 0.1
dwa: false
vx_samples: 4
vtheta_samples: 20
max_vel_x: 1.0
min_vel_x: 0.3
max_vel_th: 1.0
min_vel_th: -1.0
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.02
user_bias: 0.1
occdist_scale: 0.0
acc_lim_th: 2.0
acc_lim_x: 1.0
acc_lim_y: 0.0
holonomic_robot: false
